### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by tips-of-mine** [InfotelGLPI/releases#13]
Dear GLPi user.

BEFORE SUBMITTING YOUR ISSUE, please make sure to read and follow these steps :

Hello,

I find your plugin very good, but I am facing some small bug (or element that not understanding)

Here is the list of what I can't do:
- "Release templates", there is no "+ Add" button
- "Rollback templates" don't save anything
- "Risk template" does not save anything
- Test template" does not save anything
- Deployment task template" does not save anything

The Plugin team.

------------
* Version of the plugin : 
2.0.3

* Version of your GLPI : 
10.0.5

* Steps to reproduce (which actions have you made) :

* Expected result :

* Actual result :

* URL of the page :

* Screenshot of the problem (if pertinent) :

**Comment by tsmr** [comment]
try with https://github.com/InfotelGLPI/releases/releases/tag/2.0.4

Release templates are temporary disabled
