### ISSUE TITLE
Templates are not working

### ISSUE THREAD

**Issue by Giudy** [InfotelGLPI/releases#15]
* Version of the plugin : 2.0.3

* Version of your GLPI : 10.0.7

* Steps to reproduce (which actions have you made) : Add a template/ use a template

* Expected result : create a template

* Actual result : while in the template area, the + button is not present. permissions (profile/release) are all set. if I add a template directly in the DB, I can see and modify it, but when I use it from a change, the tasks are not created.che
* I have the same behavior in several GLPIs (10.0.6 and 10.0.7): none of them works

I'm not dure of the usage of the button "Finalize" in the finalization tab

**Comment by tsmr** [comment]
try with https://github.com/InfotelGLPI/releases/releases/tag/2.0.4

Templates are temporary disabled
