### ISSUE TITLE
[Release management] Display issue affecting other plugins.

### ISSUE THREAD

**Issue by apatec-support** [InfotelGLPI/releases#16]
------------
* Version of the plugin : 
2.0.3

* Version of your GLPI : 
10.0.9

* Steps to reproduce (which actions have you made) :
1 - At the standard interface level, the asterisks (indicating mandatory fields) on the service catalog forms are highlighted in red.
2 - When adding a risk, a rollback, a deployment task, or a test, the display is incorrect. The blocks are also not of the same size.

* Expected result :
Correction of these 2 issues will be included in a patch or a new version of the plugin.

* Actual result :
Incorrect display - impact on other plugins (FormCreator).

* URL of the page :
https://localhost/marketplace/releases/front/release.form.php?id=1
https://localhost//marketplace/formcreator/front/formdisplay.php?id=91

* Screenshot of the problem (if pertinent) :
![image](https://github.com/InfotelGLPI/releases/assets/141726211/ee7cf26c-2e5c-46e0-91d8-9c081284ccb8)
<img width="383" alt="mep-error" src="https://github.com/InfotelGLPI/releases/assets/141726211/dd9c5291-8966-49f4-b2f1-ed801986a7e6">

**Comment by tsmr** [comment]
try with https://github.com/InfotelGLPI/releases/releases/tag/2.0.4
