### ISSUE TITLE
Warnings display

### ISSUE THREAD

**Issue by Chouille** [InfotelGLPI/releases#17]
* Version of the plugin : 2.0.3
* Version of your GLPI : 10.0.10

A warning is displayed on some pages : _Warning: Unknown field: 'isNewItem' in C:\laragon\www\glpi10010-kbv2\src\CommonITILObject.php on line 269_
* Steps to reproduce (which actions have you made) :

- Create a release item => Warning display in form
- Or Display a release

* Actual result :
![image](https://github.com/InfotelGLPI/releases/assets/22129574/517e1795-d0da-4ba6-8ff6-2060607f3eb6)

* URL of the page : /marketplace/releases/front/release.form.php?id=1

**Comment by Elric59** [comment]
Hi :)

The correction gonna be upload this day
