### ISSUE TITLE
page / list of non-existent reviews

### ISSUE THREAD

**Issue by A4IDylan** [InfotelGLPI/releases#19]
Hello,

When I write a review on a production request, it is not displayed once validated, and it is impossible to find the written review.
Page does not exist: 'marketplace/releases/front/review.php'

* Version of the plugin : Version 2.0.3

* Version of your GLPI : GLPI 10.0.10

* Steps to reproduce (which actions have you made) : Writing a change review 

* Expected result : Visualize the previous review and access the different reviews (if any) via the expected releases/front/review.php page.

* Actual result : Review not visible and page non-existent

* URL of the page : marketplace/releases/front/review.php

* Screenshot of the problem (if pertinent) : 

![image](https://github.com/InfotelGLPI/releases/assets/93929836/614422dd-6b66-493c-a6d0-91075c12a0a0)

**Comment by tsmr** [comment]
try with https://github.com/InfotelGLPI/releases/releases/tag/2.0.4
