### ISSUE TITLE
No add button

### ISSUE THREAD

**Issue by valyuzgit** [InfotelGLPI/releases#4]
Dear GLPi user.

BEFORE SUBMITTING YOUR ISSUE, please make sure to read and follow these steps :

* Verify that your question has not already been asked
* Please use the below template.
* Delete this text before submiting your issue.

The Plugin team.

------------
* Version of the plugin : 

Releases | releases | 1.0.0 | GPLv2+ | Enabled | Infotel, Alban Lesellier

* Version of your GLPI : 
GLPI 9.5.1 Copyright (C) 2015-2020 Teclib' and contributors
FusionInventory 9.5.0+1.0 - Copyleft © 2010-2019 by FusionInventory Team

* Steps to reproduce (which actions have you made) :
Click on Create a Release.

* Expected result :
Must be add button
![image](https://user-images.githubusercontent.com/72557487/95459303-210c9700-097c-11eb-968b-a034677eaff0.png)

* Actual result :
No Add button, can't submit the release.

* URL of the page :

* Screenshot of the problem (if pertinent) :

![image](https://user-images.githubusercontent.com/72557487/95459043-bc513c80-097b-11eb-970e-443f30b3eaef.png)

**Comment by gguib** [comment]
Hi, 

Does the error still persists ?
I can't reproduce your bug. 
Have you check your profiles rights first ? Some browsers errors log ?
